-- AlterTable
ALTER TABLE `submittals` MODIFY `status` ENUM('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'APPROVED', 'APPROVED_WITH_COMMENTS', 'REJECTED', 'REVISE_AND_RESUBMIT', 'CLOSED') NOT NULL DEFAULT 'DRAFT';
